# Copyright (c) 2026 wmrsouza@hotmail.com
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

# CONFIG_SENSOR=y
# CONFIG_BLINK=y

CONFIG_LOG=y
# CONFIG_APP_LOG_LEVEL_ERR=y /* 1 */
# CONFIG_APP_LOG_LEVEL_WRN=y /* 2 */
# CONFIG_APP_LOG_LEVEL_INF=y /* 3 */
# CONFIG_APP_LOG_LEVEL_DBG=y /* 4 */

# CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG_MODE_IMMEDIATE=y
# CONFIG_LOG_MODE_DEFERRED=y
